apisix:
  node_listen: 9080
  enable_admin: true
  admin_listen: 9180
  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin

etcd:
  host:
    - "kit-etcd:2379"  # Usar el nombre del servicio en la red Docker
  prefix: "/apisix"
  timeout: 30
