version: '3'
services:
  apisix:
    image: apache/apisix:2.15.0-alpine
    restart: always
    volumes:
      - ./apisix-config.yaml:/usr/local/apisix/conf/config.yaml:ro
    environment:
      - APISIX_STAND_ALONE=true
    ports:
      - "9080:9080"
      - "9180:9180"
    networks:
      - rantipay-network

networks:
  rantipay-network:
    external: true
