version: '3.7'

services:
  user:
    volumes:
      - ./user:/app/user
    environment:
      - DATA_DATABASE_SOURCE=root:youShouldChangeThis@tcp(mysqld:3306)/user_db
      - ETCD_ADDRESS=etcd:2379
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=youShouldChangeThis
    restart: on-failure

  saas:
    volumes:
      - ./saas:/app/saas
    environment:
      - DATA_DATABASE_SOURCE=root:youShouldChangeThis@tcp(mysqld:3306)/saas_db
      - ETCD_ADDRESS=etcd:2379
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=youShouldChangeThis
    restart: on-failure

  sys:
    volumes:
      - ./sys:/app/sys
    environment:
      - DATA_DATABASE_SOURCE=root:youShouldChangeThis@tcp(mysqld:3306)/sys_db
      - ETCD_ADDRESS=etcd:2379
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=youShouldChangeThis
    restart: on-failure
