version: '3.7'
services:
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  user:
    image: simple-user:debug
    ports:
      - "8000:8000"
    volumes:
      - ./configs:/data/conf
      - ./kit/quickstart/.assets:/app/.assets
    restart: unless-stopped

  web:
    image: goxiaoy/go-saas-kit-frontend:dev
    ports:
      - "8080:80"
    volumes:
      - ./kit-frontend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  mysqld:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=youShouldChangeThis
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3406:3306"
    restart: unless-stopped

  redis:
    image: redis:6.0
    command: redis-server --requirepass youShouldChangeThis
    ports:
      - "7379:6379"
    restart: unless-stopped

volumes:
  mysql_data:
