FROM golang:1.20 AS builder
WORKDIR /app
COPY . .
RUN go build -o app main.go

FROM debian:stable-slim
RUN apt-get update && apt-get install -y ca-certificates curl net-tools procps && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/app .
EXPOSE 8000
CMD ["/app/app"]
