// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: stripe/stripe.proto

package stripe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsTest        bool                   `protobuf:"varint,1,opt,name=is_test,json=isTest,proto3" json:"is_test,omitempty"`
	PublishKey    string                 `protobuf:"bytes,2,opt,name=publish_key,json=publishKey,proto3" json:"publish_key,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	WebhookKey    string                 `protobuf:"bytes,4,opt,name=webhook_key,json=webhookKey,proto3" json:"webhook_key,omitempty"`
	PriceTables   map[string]string      `protobuf:"bytes,5,rep,name=price_tables,json=priceTables,proto3" json:"price_tables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conf) Reset() {
	*x = Conf{}
	mi := &file_stripe_stripe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conf) ProtoMessage() {}

func (x *Conf) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_stripe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conf.ProtoReflect.Descriptor instead.
func (*Conf) Descriptor() ([]byte, []int) {
	return file_stripe_stripe_proto_rawDescGZIP(), []int{0}
}

func (x *Conf) GetIsTest() bool {
	if x != nil {
		return x.IsTest
	}
	return false
}

func (x *Conf) GetPublishKey() string {
	if x != nil {
		return x.PublishKey
	}
	return ""
}

func (x *Conf) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *Conf) GetWebhookKey() string {
	if x != nil {
		return x.WebhookKey
	}
	return ""
}

func (x *Conf) GetPriceTables() map[string]string {
	if x != nil {
		return x.PriceTables
	}
	return nil
}

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentIntent *PaymentIntent         `protobuf:"bytes,10,opt,name=payment_intent,json=paymentIntent,proto3" json:"payment_intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_stripe_stripe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_stripe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_stripe_stripe_proto_rawDescGZIP(), []int{1}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetPaymentIntent() *PaymentIntent {
	if x != nil {
		return x.PaymentIntent
	}
	return nil
}

type PaymentIntent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentIntent) Reset() {
	*x = PaymentIntent{}
	mi := &file_stripe_stripe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentIntent) ProtoMessage() {}

func (x *PaymentIntent) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_stripe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentIntent.ProtoReflect.Descriptor instead.
func (*PaymentIntent) Descriptor() ([]byte, []int) {
	return file_stripe_stripe_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentIntent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentIntent) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *PaymentIntent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LatestInvoice *Invoice               `protobuf:"bytes,100,opt,name=latest_invoice,json=latestInvoice,proto3" json:"latest_invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_stripe_stripe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_stripe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_stripe_stripe_proto_rawDescGZIP(), []int{3}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetLatestInvoice() *Invoice {
	if x != nil {
		return x.LatestInvoice
	}
	return nil
}

type EphemeralKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EphemeralKey) Reset() {
	*x = EphemeralKey{}
	mi := &file_stripe_stripe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EphemeralKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EphemeralKey) ProtoMessage() {}

func (x *EphemeralKey) ProtoReflect() protoreflect.Message {
	mi := &file_stripe_stripe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EphemeralKey.ProtoReflect.Descriptor instead.
func (*EphemeralKey) Descriptor() ([]byte, []int) {
	return file_stripe_stripe_proto_rawDescGZIP(), []int{4}
}

func (x *EphemeralKey) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_stripe_stripe_proto protoreflect.FileDescriptor

const file_stripe_stripe_proto_rawDesc = "" +
	"\n" +
	"\x13stripe/stripe.proto\x12\x06stripe\"\x84\x02\n" +
	"\x04Conf\x12\x17\n" +
	"\ais_test\x18\x01 \x01(\bR\x06isTest\x12\x1f\n" +
	"\vpublish_key\x18\x02 \x01(\tR\n" +
	"publishKey\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12\x1f\n" +
	"\vwebhook_key\x18\x04 \x01(\tR\n" +
	"webhookKey\x12@\n" +
	"\fprice_tables\x18\x05 \x03(\v2\x1d.stripe.Conf.PriceTablesEntryR\vpriceTables\x1a>\n" +
	"\x10PriceTablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\x0epayment_intent\x18\n" +
	" \x01(\v2\x15.stripe.PaymentIntentR\rpaymentIntent\"\\\n" +
	"\rPaymentIntent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"V\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x0elatest_invoice\x18d \x01(\v2\x0f.stripe.InvoiceR\rlatestInvoice\"&\n" +
	"\fEphemeralKey\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secretB*Z(github.com/go-saas/kit/pkg/stripe;stripeb\x06proto3"

var (
	file_stripe_stripe_proto_rawDescOnce sync.Once
	file_stripe_stripe_proto_rawDescData []byte
)

func file_stripe_stripe_proto_rawDescGZIP() []byte {
	file_stripe_stripe_proto_rawDescOnce.Do(func() {
		file_stripe_stripe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stripe_stripe_proto_rawDesc), len(file_stripe_stripe_proto_rawDesc)))
	})
	return file_stripe_stripe_proto_rawDescData
}

var file_stripe_stripe_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stripe_stripe_proto_goTypes = []any{
	(*Conf)(nil),          // 0: stripe.Conf
	(*Invoice)(nil),       // 1: stripe.Invoice
	(*PaymentIntent)(nil), // 2: stripe.PaymentIntent
	(*Subscription)(nil),  // 3: stripe.Subscription
	(*EphemeralKey)(nil),  // 4: stripe.EphemeralKey
	nil,                   // 5: stripe.Conf.PriceTablesEntry
}
var file_stripe_stripe_proto_depIdxs = []int32{
	5, // 0: stripe.Conf.price_tables:type_name -> stripe.Conf.PriceTablesEntry
	2, // 1: stripe.Invoice.payment_intent:type_name -> stripe.PaymentIntent
	1, // 2: stripe.Subscription.latest_invoice:type_name -> stripe.Invoice
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stripe_stripe_proto_init() }
func file_stripe_stripe_proto_init() {
	if File_stripe_stripe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stripe_stripe_proto_rawDesc), len(file_stripe_stripe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stripe_stripe_proto_goTypes,
		DependencyIndexes: file_stripe_stripe_proto_depIdxs,
		MessageInfos:      file_stripe_stripe_proto_msgTypes,
	}.Build()
	File_stripe_stripe_proto = out.File
	file_stripe_stripe_proto_goTypes = nil
	file_stripe_stripe_proto_depIdxs = nil
}
