// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: google/api/servicecontrol/v1/quota_controller.proto

package servicecontrolpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AllocateQuotaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AllocateQuotaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AllocateQuotaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AllocateQuotaRequestMultiError, or nil if none found.
func (m *AllocateQuotaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AllocateQuotaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ServiceName

	if all {
		switch v := interface{}(m.GetAllocateOperation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AllocateQuotaRequestValidationError{
					field:  "AllocateOperation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AllocateQuotaRequestValidationError{
					field:  "AllocateOperation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAllocateOperation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AllocateQuotaRequestValidationError{
				field:  "AllocateOperation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ServiceConfigId

	if len(errors) > 0 {
		return AllocateQuotaRequestMultiError(errors)
	}

	return nil
}

// AllocateQuotaRequestMultiError is an error wrapping multiple validation
// errors returned by AllocateQuotaRequest.ValidateAll() if the designated
// constraints aren't met.
type AllocateQuotaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AllocateQuotaRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AllocateQuotaRequestMultiError) AllErrors() []error { return m }

// AllocateQuotaRequestValidationError is the validation error returned by
// AllocateQuotaRequest.Validate if the designated constraints aren't met.
type AllocateQuotaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AllocateQuotaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AllocateQuotaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AllocateQuotaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AllocateQuotaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AllocateQuotaRequestValidationError) ErrorName() string {
	return "AllocateQuotaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AllocateQuotaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAllocateQuotaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AllocateQuotaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AllocateQuotaRequestValidationError{}

// Validate checks the field values on QuotaOperation with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QuotaOperation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QuotaOperation with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QuotaOperationMultiError,
// or nil if none found.
func (m *QuotaOperation) ValidateAll() error {
	return m.validate(true)
}

func (m *QuotaOperation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OperationId

	// no validation rules for MethodName

	// no validation rules for ConsumerId

	// no validation rules for Labels

	for idx, item := range m.GetQuotaMetrics() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QuotaOperationValidationError{
						field:  fmt.Sprintf("QuotaMetrics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QuotaOperationValidationError{
						field:  fmt.Sprintf("QuotaMetrics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QuotaOperationValidationError{
					field:  fmt.Sprintf("QuotaMetrics[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for QuotaMode

	if len(errors) > 0 {
		return QuotaOperationMultiError(errors)
	}

	return nil
}

// QuotaOperationMultiError is an error wrapping multiple validation errors
// returned by QuotaOperation.ValidateAll() if the designated constraints
// aren't met.
type QuotaOperationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QuotaOperationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QuotaOperationMultiError) AllErrors() []error { return m }

// QuotaOperationValidationError is the validation error returned by
// QuotaOperation.Validate if the designated constraints aren't met.
type QuotaOperationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QuotaOperationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QuotaOperationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QuotaOperationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QuotaOperationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QuotaOperationValidationError) ErrorName() string { return "QuotaOperationValidationError" }

// Error satisfies the builtin error interface
func (e QuotaOperationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuotaOperation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QuotaOperationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QuotaOperationValidationError{}

// Validate checks the field values on AllocateQuotaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AllocateQuotaResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AllocateQuotaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AllocateQuotaResponseMultiError, or nil if none found.
func (m *AllocateQuotaResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AllocateQuotaResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OperationId

	for idx, item := range m.GetAllocateErrors() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AllocateQuotaResponseValidationError{
						field:  fmt.Sprintf("AllocateErrors[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AllocateQuotaResponseValidationError{
						field:  fmt.Sprintf("AllocateErrors[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AllocateQuotaResponseValidationError{
					field:  fmt.Sprintf("AllocateErrors[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetQuotaMetrics() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AllocateQuotaResponseValidationError{
						field:  fmt.Sprintf("QuotaMetrics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AllocateQuotaResponseValidationError{
						field:  fmt.Sprintf("QuotaMetrics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AllocateQuotaResponseValidationError{
					field:  fmt.Sprintf("QuotaMetrics[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for ServiceConfigId

	if len(errors) > 0 {
		return AllocateQuotaResponseMultiError(errors)
	}

	return nil
}

// AllocateQuotaResponseMultiError is an error wrapping multiple validation
// errors returned by AllocateQuotaResponse.ValidateAll() if the designated
// constraints aren't met.
type AllocateQuotaResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AllocateQuotaResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AllocateQuotaResponseMultiError) AllErrors() []error { return m }

// AllocateQuotaResponseValidationError is the validation error returned by
// AllocateQuotaResponse.Validate if the designated constraints aren't met.
type AllocateQuotaResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AllocateQuotaResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AllocateQuotaResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AllocateQuotaResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AllocateQuotaResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AllocateQuotaResponseValidationError) ErrorName() string {
	return "AllocateQuotaResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AllocateQuotaResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAllocateQuotaResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AllocateQuotaResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AllocateQuotaResponseValidationError{}

// Validate checks the field values on QuotaError with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QuotaError) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QuotaError with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QuotaErrorMultiError, or
// nil if none found.
func (m *QuotaError) ValidateAll() error {
	return m.validate(true)
}

func (m *QuotaError) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Subject

	// no validation rules for Description

	if all {
		switch v := interface{}(m.GetStatus()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QuotaErrorValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QuotaErrorValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QuotaErrorValidationError{
				field:  "Status",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return QuotaErrorMultiError(errors)
	}

	return nil
}

// QuotaErrorMultiError is an error wrapping multiple validation errors
// returned by QuotaError.ValidateAll() if the designated constraints aren't met.
type QuotaErrorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QuotaErrorMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QuotaErrorMultiError) AllErrors() []error { return m }

// QuotaErrorValidationError is the validation error returned by
// QuotaError.Validate if the designated constraints aren't met.
type QuotaErrorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QuotaErrorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QuotaErrorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QuotaErrorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QuotaErrorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QuotaErrorValidationError) ErrorName() string { return "QuotaErrorValidationError" }

// Error satisfies the builtin error interface
func (e QuotaErrorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuotaError.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QuotaErrorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QuotaErrorValidationError{}
