// Code generated by protoc-gen-go-grpc-proxy. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc-proxy v1.2.0
// - protoc             (unknown)
// source: google/api/servicecontrol/v1/quota_controller.proto

package servicecontrolpb

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

var _ QuotaControllerServer = (*quotaControllerClientProxy)(nil)

// quotaControllerClientProxy is the proxy to turn QuotaController client to server interface.
type quotaControllerClientProxy struct {
	cc QuotaControllerClient
}

func NewQuotaControllerClientProxy(cc QuotaControllerClient) QuotaControllerServer {
	return &quotaControllerClientProxy{cc}
}

func (c *quotaControllerClientProxy) AllocateQuota(ctx context.Context, in *AllocateQuotaRequest) (*AllocateQuotaResponse, error) {
	return c.cc.AllocateQuota(ctx, in)
}
