services:
  # NGINX como API Gateway
  nginx:
    image: nginx:1.21
    ports:
      - "81:80"
    volumes:
      - ./nginx-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - app-network

  # Servicio User
  user:
    image: goxiaoy/go-saas-kit-user:latest
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      - APP_ENV=dev
    volumes:
      - ./configs:/data/conf
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mysqld
      - redis

  # Servicio SaaS
  saas:
    image: goxiaoy/go-saas-kit-saas:latest
    ports:
      - "8002:8000"
      - "9002:9000"
    environment:
      - APP_ENV=dev
    volumes:
      - ./configs:/data/conf
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mysqld
      - redis
      - user

  # Servicio Sys
  sys:
    image: goxiaoy/go-saas-kit-sys:latest
    ports:
      - "8003:8000"
      - "9003:9000"
    environment:
      - APP_ENV=dev
    volumes:
      - ./configs:/data/conf
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mysqld
      - redis
      - user

  # Frontend
  web:
    image: goxiaoy/go-saas-kit-frontend:dev
    ports:
      - "8080:80"
    volumes:
      - ./kit-frontend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    depends_on:
      - nginx
    networks:
      - app-network

  # Base de datos
  mysqld:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=youShouldChangeThis
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=kit
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3406:3306"
    restart: unless-stopped
    networks:
      - app-network

  # Cache
  redis:
    image: redis:6.0
    command: redis-server --requirepass youShouldChangeThis
    ports:
      - "7379:6379"
    restart: unless-stopped
    networks:
      - app-network

  # Etcd para service discovery
  etcd:
    image: bitnami/etcd:3.5.0
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "3379:2379"
    volumes:
      - etcd_data:/bitnami/etcd
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  etcd_data:
