// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: google/api/expr/conformance/v1alpha1/conformance_service.proto

package confpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	v1alpha1 "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severities of issues.
type IssueDetails_Severity int32

const (
	// An unspecified severity.
	IssueDetails_SEVERITY_UNSPECIFIED IssueDetails_Severity = 0
	// Deprecation issue for statements and method that may no longer be
	// supported or maintained.
	IssueDetails_DEPRECATION IssueDetails_Severity = 1
	// Warnings such as: unused variables.
	IssueDetails_WARNING IssueDetails_Severity = 2
	// Errors such as: unmatched curly braces or variable redefinition.
	IssueDetails_ERROR IssueDetails_Severity = 3
)

// Enum value maps for IssueDetails_Severity.
var (
	IssueDetails_Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "DEPRECATION",
		2: "WARNING",
		3: "ERROR",
	}
	IssueDetails_Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"DEPRECATION":          1,
		"WARNING":              2,
		"ERROR":                3,
	}
)

func (x IssueDetails_Severity) Enum() *IssueDetails_Severity {
	p := new(IssueDetails_Severity)
	*p = x
	return p
}

func (x IssueDetails_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IssueDetails_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_google_api_expr_conformance_v1alpha1_conformance_service_proto_enumTypes[0].Descriptor()
}

func (IssueDetails_Severity) Type() protoreflect.EnumType {
	return &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_enumTypes[0]
}

func (x IssueDetails_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IssueDetails_Severity.Descriptor instead.
func (IssueDetails_Severity) EnumDescriptor() ([]byte, []int) {
	return file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescGZIP(), []int{7, 0}
}

// Request message for the Parse method.
type ParseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Source text in CEL syntax.
	CelSource string `protobuf:"bytes,1,opt,name=cel_source,json=celSource,proto3" json:"cel_source,omitempty"`
	// Tag for version of CEL syntax, for future use.
	SyntaxVersion string `protobuf:"bytes,2,opt,name=syntax_version,json=syntaxVersion,proto3" json:"syntax_version,omitempty"`
	// File or resource for source text, used in [SourceInfo][google.api.SourceInfo].
	SourceLocation string `protobuf:"bytes,3,opt,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	// Prevent macro expansion.  See "Macros" in Language Defiinition.
	DisableMacros bool `protobuf:"varint,4,opt,name=disable_macros,json=disableMacros,proto3" json:"disable_macros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetCelSource() string {
	if x != nil {
		return x.CelSource
	}
	return ""
}

func (x *ParseRequest) GetSyntaxVersion() string {
	if x != nil {
		return x.SyntaxVersion
	}
	return ""
}

func (x *ParseRequest) GetSourceLocation() string {
	if x != nil {
		return x.SourceLocation
	}
	return ""
}

func (x *ParseRequest) GetDisableMacros() bool {
	if x != nil {
		return x.DisableMacros
	}
	return false
}

// Response message for the Parse method.
type ParseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parsed representation, or unset if parsing failed.
	ParsedExpr *v1alpha1.ParsedExpr `protobuf:"bytes,1,opt,name=parsed_expr,json=parsedExpr,proto3" json:"parsed_expr,omitempty"`
	// Any number of issues with [StatusDetails][] as the details.
	Issues        []*status.Status `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResponse) GetParsedExpr() *v1alpha1.ParsedExpr {
	if x != nil {
		return x.ParsedExpr
	}
	return nil
}

func (x *ParseResponse) GetIssues() []*status.Status {
	if x != nil {
		return x.Issues
	}
	return nil
}

// Request message for the Check method.
type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The parsed representation of the CEL program.
	ParsedExpr *v1alpha1.ParsedExpr `protobuf:"bytes,1,opt,name=parsed_expr,json=parsedExpr,proto3" json:"parsed_expr,omitempty"`
	// Declarations of types for external variables and functions.
	// Required if program uses external variables or functions
	// not in the default environment.
	TypeEnv []*v1alpha1.Decl `protobuf:"bytes,2,rep,name=type_env,json=typeEnv,proto3" json:"type_env,omitempty"`
	// The protocol buffer context.  See "Name Resolution" in the
	// Language Definition.
	Container string `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	// If true, use only the declarations in [type_env][google.api.expr.conformance.v1alpha1.CheckRequest.type_env].  If false (default),
	// add declarations for the standard definitions to the type environment.  See
	// "Standard Definitions" in the Language Definition.
	NoStdEnv      bool `protobuf:"varint,4,opt,name=no_std_env,json=noStdEnv,proto3" json:"no_std_env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetParsedExpr() *v1alpha1.ParsedExpr {
	if x != nil {
		return x.ParsedExpr
	}
	return nil
}

func (x *CheckRequest) GetTypeEnv() []*v1alpha1.Decl {
	if x != nil {
		return x.TypeEnv
	}
	return nil
}

func (x *CheckRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *CheckRequest) GetNoStdEnv() bool {
	if x != nil {
		return x.NoStdEnv
	}
	return false
}

// Response message for the Check method.
type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The annotated representation, or unset if checking failed.
	CheckedExpr *v1alpha1.CheckedExpr `protobuf:"bytes,1,opt,name=checked_expr,json=checkedExpr,proto3" json:"checked_expr,omitempty"`
	// Any number of issues with [StatusDetails][] as the details.
	Issues        []*status.Status `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetCheckedExpr() *v1alpha1.CheckedExpr {
	if x != nil {
		return x.CheckedExpr
	}
	return nil
}

func (x *CheckResponse) GetIssues() []*status.Status {
	if x != nil {
		return x.Issues
	}
	return nil
}

// Request message for the Eval method.
type EvalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Either the parsed or annotated representation of the CEL program.
	//
	// Types that are valid to be assigned to ExprKind:
	//
	//	*EvalRequest_ParsedExpr
	//	*EvalRequest_CheckedExpr
	ExprKind isEvalRequest_ExprKind `protobuf_oneof:"expr_kind"`
	// Bindings for the external variables.  The types SHOULD be compatible
	// with the type environment in [CheckRequest][google.api.expr.conformance.v1alpha1.CheckRequest], if checked.
	Bindings map[string]*v1alpha1.ExprValue `protobuf:"bytes,3,rep,name=bindings,proto3" json:"bindings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// SHOULD be the same container as used in [CheckRequest][google.api.expr.conformance.v1alpha1.CheckRequest], if checked.
	Container     string `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalRequest) Reset() {
	*x = EvalRequest{}
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalRequest) ProtoMessage() {}

func (x *EvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalRequest.ProtoReflect.Descriptor instead.
func (*EvalRequest) Descriptor() ([]byte, []int) {
	return file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescGZIP(), []int{4}
}

func (x *EvalRequest) GetExprKind() isEvalRequest_ExprKind {
	if x != nil {
		return x.ExprKind
	}
	return nil
}

func (x *EvalRequest) GetParsedExpr() *v1alpha1.ParsedExpr {
	if x != nil {
		if x, ok := x.ExprKind.(*EvalRequest_ParsedExpr); ok {
			return x.ParsedExpr
		}
	}
	return nil
}

func (x *EvalRequest) GetCheckedExpr() *v1alpha1.CheckedExpr {
	if x != nil {
		if x, ok := x.ExprKind.(*EvalRequest_CheckedExpr); ok {
			return x.CheckedExpr
		}
	}
	return nil
}

func (x *EvalRequest) GetBindings() map[string]*v1alpha1.ExprValue {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *EvalRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type isEvalRequest_ExprKind interface {
	isEvalRequest_ExprKind()
}

type EvalRequest_ParsedExpr struct {
	// Evaluate based on the parsed representation.
	ParsedExpr *v1alpha1.ParsedExpr `protobuf:"bytes,1,opt,name=parsed_expr,json=parsedExpr,proto3,oneof"`
}

type EvalRequest_CheckedExpr struct {
	// Evaluate based on the checked representation.
	CheckedExpr *v1alpha1.CheckedExpr `protobuf:"bytes,2,opt,name=checked_expr,json=checkedExpr,proto3,oneof"`
}

func (*EvalRequest_ParsedExpr) isEvalRequest_ExprKind() {}

func (*EvalRequest_CheckedExpr) isEvalRequest_ExprKind() {}

// Response message for the Eval method.
type EvalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The execution result, or unset if execution couldn't start.
	Result *v1alpha1.ExprValue `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Any number of issues with [StatusDetails][] as the details.
	// Note that CEL execution errors are reified into [ExprValue][].
	// Nevertheless, we'll allow out-of-band issues to be raised,
	// which also makes the replies more regular.
	Issues        []*status.Status `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalResponse) Reset() {
	*x = EvalResponse{}
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalResponse) ProtoMessage() {}

func (x *EvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalResponse.ProtoReflect.Descriptor instead.
func (*EvalResponse) Descriptor() ([]byte, []int) {
	return file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescGZIP(), []int{5}
}

func (x *EvalResponse) GetResult() *v1alpha1.ExprValue {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *EvalResponse) GetIssues() []*status.Status {
	if x != nil {
		return x.Issues
	}
	return nil
}

// A specific position in source.
type SourcePosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source location name (e.g. file name).
	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// The UTF-8 code unit offset.
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// The 1-based index of the starting line in the source text
	// where the issue occurs, or 0 if unknown.
	Line int32 `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	// The 0-based index of the starting position within the line of source text
	// where the issue occurs.  Only meaningful if line is nonzero.
	Column        int32 `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcePosition) Reset() {
	*x = SourcePosition{}
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcePosition) ProtoMessage() {}

func (x *SourcePosition) ProtoReflect() protoreflect.Message {
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcePosition.ProtoReflect.Descriptor instead.
func (*SourcePosition) Descriptor() ([]byte, []int) {
	return file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescGZIP(), []int{6}
}

func (x *SourcePosition) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SourcePosition) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SourcePosition) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *SourcePosition) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// Warnings or errors in service execution are represented by
// [google.rpc.Status][google.rpc.Status] messages, with the following message
// in the details field.
type IssueDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The severity of the issue.
	Severity IssueDetails_Severity `protobuf:"varint,1,opt,name=severity,proto3,enum=google.api.expr.conformance.v1alpha1.IssueDetails_Severity" json:"severity,omitempty"`
	// Position in the source, if known.
	Position *SourcePosition `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	// Expression ID from [Expr][], 0 if unknown.
	Id            int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueDetails) Reset() {
	*x = IssueDetails{}
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueDetails) ProtoMessage() {}

func (x *IssueDetails) ProtoReflect() protoreflect.Message {
	mi := &file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueDetails.ProtoReflect.Descriptor instead.
func (*IssueDetails) Descriptor() ([]byte, []int) {
	return file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescGZIP(), []int{7}
}

func (x *IssueDetails) GetSeverity() IssueDetails_Severity {
	if x != nil {
		return x.Severity
	}
	return IssueDetails_SEVERITY_UNSPECIFIED
}

func (x *IssueDetails) GetPosition() *SourcePosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *IssueDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_google_api_expr_conformance_v1alpha1_conformance_service_proto protoreflect.FileDescriptor

const file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDesc = "" +
	"\n" +
	">google/api/expr/conformance/v1alpha1/conformance_service.proto\x12$google.api.expr.conformance.v1alpha1\x1a\x17google/api/client.proto\x1a&google/api/expr/v1alpha1/checked.proto\x1a#google/api/expr/v1alpha1/eval.proto\x1a%google/api/expr/v1alpha1/syntax.proto\x1a\x1egoogle/rpc/status/status.proto\"\xa4\x01\n" +
	"\fParseRequest\x12\x1d\n" +
	"\n" +
	"cel_source\x18\x01 \x01(\tR\tcelSource\x12%\n" +
	"\x0esyntax_version\x18\x02 \x01(\tR\rsyntaxVersion\x12'\n" +
	"\x0fsource_location\x18\x03 \x01(\tR\x0esourceLocation\x12%\n" +
	"\x0edisable_macros\x18\x04 \x01(\bR\rdisableMacros\"\x82\x01\n" +
	"\rParseResponse\x12E\n" +
	"\vparsed_expr\x18\x01 \x01(\v2$.google.api.expr.v1alpha1.ParsedExprR\n" +
	"parsedExpr\x12*\n" +
	"\x06issues\x18\x02 \x03(\v2\x12.google.rpc.StatusR\x06issues\"\xcc\x01\n" +
	"\fCheckRequest\x12E\n" +
	"\vparsed_expr\x18\x01 \x01(\v2$.google.api.expr.v1alpha1.ParsedExprR\n" +
	"parsedExpr\x129\n" +
	"\btype_env\x18\x02 \x03(\v2\x1e.google.api.expr.v1alpha1.DeclR\atypeEnv\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x1c\n" +
	"\n" +
	"no_std_env\x18\x04 \x01(\bR\bnoStdEnv\"\x85\x01\n" +
	"\rCheckResponse\x12H\n" +
	"\fchecked_expr\x18\x01 \x01(\v2%.google.api.expr.v1alpha1.CheckedExprR\vcheckedExpr\x12*\n" +
	"\x06issues\x18\x02 \x03(\v2\x12.google.rpc.StatusR\x06issues\"\x8c\x03\n" +
	"\vEvalRequest\x12G\n" +
	"\vparsed_expr\x18\x01 \x01(\v2$.google.api.expr.v1alpha1.ParsedExprH\x00R\n" +
	"parsedExpr\x12J\n" +
	"\fchecked_expr\x18\x02 \x01(\v2%.google.api.expr.v1alpha1.CheckedExprH\x00R\vcheckedExpr\x12[\n" +
	"\bbindings\x18\x03 \x03(\v2?.google.api.expr.conformance.v1alpha1.EvalRequest.BindingsEntryR\bbindings\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x1a`\n" +
	"\rBindingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.google.api.expr.v1alpha1.ExprValueR\x05value:\x028\x01B\v\n" +
	"\texpr_kind\"w\n" +
	"\fEvalResponse\x12;\n" +
	"\x06result\x18\x01 \x01(\v2#.google.api.expr.v1alpha1.ExprValueR\x06result\x12*\n" +
	"\x06issues\x18\x02 \x03(\v2\x12.google.rpc.StatusR\x06issues\"p\n" +
	"\x0eSourcePosition\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\"\x98\x02\n" +
	"\fIssueDetails\x12W\n" +
	"\bseverity\x18\x01 \x01(\x0e2;.google.api.expr.conformance.v1alpha1.IssueDetails.SeverityR\bseverity\x12P\n" +
	"\bposition\x18\x02 \x01(\v24.google.api.expr.conformance.v1alpha1.SourcePositionR\bposition\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"M\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDEPRECATION\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\x84\x03\n" +
	"\x12ConformanceService\x12r\n" +
	"\x05Parse\x122.google.api.expr.conformance.v1alpha1.ParseRequest\x1a3.google.api.expr.conformance.v1alpha1.ParseResponse\"\x00\x12r\n" +
	"\x05Check\x122.google.api.expr.conformance.v1alpha1.CheckRequest\x1a3.google.api.expr.conformance.v1alpha1.CheckResponse\"\x00\x12o\n" +
	"\x04Eval\x121.google.api.expr.conformance.v1alpha1.EvalRequest\x1a2.google.api.expr.conformance.v1alpha1.EvalResponse\"\x00\x1a\x15\xcaA\x12cel.googleapis.comB\x94\x01\n" +
	"(com.google.api.expr.conformance.v1alpha1B\x17ConformanceServiceProtoP\x01ZJgoogle.golang.org/genproto/googleapis/api/expr/conformance/v1alpha1;confpb\xf8\x01\x01b\x06proto3"

var (
	file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescOnce sync.Once
	file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescData []byte
)

func file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescGZIP() []byte {
	file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescOnce.Do(func() {
		file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDesc), len(file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDesc)))
	})
	return file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDescData
}

var file_google_api_expr_conformance_v1alpha1_conformance_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_google_api_expr_conformance_v1alpha1_conformance_service_proto_goTypes = []any{
	(IssueDetails_Severity)(0),   // 0: google.api.expr.conformance.v1alpha1.IssueDetails.Severity
	(*ParseRequest)(nil),         // 1: google.api.expr.conformance.v1alpha1.ParseRequest
	(*ParseResponse)(nil),        // 2: google.api.expr.conformance.v1alpha1.ParseResponse
	(*CheckRequest)(nil),         // 3: google.api.expr.conformance.v1alpha1.CheckRequest
	(*CheckResponse)(nil),        // 4: google.api.expr.conformance.v1alpha1.CheckResponse
	(*EvalRequest)(nil),          // 5: google.api.expr.conformance.v1alpha1.EvalRequest
	(*EvalResponse)(nil),         // 6: google.api.expr.conformance.v1alpha1.EvalResponse
	(*SourcePosition)(nil),       // 7: google.api.expr.conformance.v1alpha1.SourcePosition
	(*IssueDetails)(nil),         // 8: google.api.expr.conformance.v1alpha1.IssueDetails
	nil,                          // 9: google.api.expr.conformance.v1alpha1.EvalRequest.BindingsEntry
	(*v1alpha1.ParsedExpr)(nil),  // 10: google.api.expr.v1alpha1.ParsedExpr
	(*status.Status)(nil),        // 11: google.rpc.Status
	(*v1alpha1.Decl)(nil),        // 12: google.api.expr.v1alpha1.Decl
	(*v1alpha1.CheckedExpr)(nil), // 13: google.api.expr.v1alpha1.CheckedExpr
	(*v1alpha1.ExprValue)(nil),   // 14: google.api.expr.v1alpha1.ExprValue
}
var file_google_api_expr_conformance_v1alpha1_conformance_service_proto_depIdxs = []int32{
	10, // 0: google.api.expr.conformance.v1alpha1.ParseResponse.parsed_expr:type_name -> google.api.expr.v1alpha1.ParsedExpr
	11, // 1: google.api.expr.conformance.v1alpha1.ParseResponse.issues:type_name -> google.rpc.Status
	10, // 2: google.api.expr.conformance.v1alpha1.CheckRequest.parsed_expr:type_name -> google.api.expr.v1alpha1.ParsedExpr
	12, // 3: google.api.expr.conformance.v1alpha1.CheckRequest.type_env:type_name -> google.api.expr.v1alpha1.Decl
	13, // 4: google.api.expr.conformance.v1alpha1.CheckResponse.checked_expr:type_name -> google.api.expr.v1alpha1.CheckedExpr
	11, // 5: google.api.expr.conformance.v1alpha1.CheckResponse.issues:type_name -> google.rpc.Status
	10, // 6: google.api.expr.conformance.v1alpha1.EvalRequest.parsed_expr:type_name -> google.api.expr.v1alpha1.ParsedExpr
	13, // 7: google.api.expr.conformance.v1alpha1.EvalRequest.checked_expr:type_name -> google.api.expr.v1alpha1.CheckedExpr
	9,  // 8: google.api.expr.conformance.v1alpha1.EvalRequest.bindings:type_name -> google.api.expr.conformance.v1alpha1.EvalRequest.BindingsEntry
	14, // 9: google.api.expr.conformance.v1alpha1.EvalResponse.result:type_name -> google.api.expr.v1alpha1.ExprValue
	11, // 10: google.api.expr.conformance.v1alpha1.EvalResponse.issues:type_name -> google.rpc.Status
	0,  // 11: google.api.expr.conformance.v1alpha1.IssueDetails.severity:type_name -> google.api.expr.conformance.v1alpha1.IssueDetails.Severity
	7,  // 12: google.api.expr.conformance.v1alpha1.IssueDetails.position:type_name -> google.api.expr.conformance.v1alpha1.SourcePosition
	14, // 13: google.api.expr.conformance.v1alpha1.EvalRequest.BindingsEntry.value:type_name -> google.api.expr.v1alpha1.ExprValue
	1,  // 14: google.api.expr.conformance.v1alpha1.ConformanceService.Parse:input_type -> google.api.expr.conformance.v1alpha1.ParseRequest
	3,  // 15: google.api.expr.conformance.v1alpha1.ConformanceService.Check:input_type -> google.api.expr.conformance.v1alpha1.CheckRequest
	5,  // 16: google.api.expr.conformance.v1alpha1.ConformanceService.Eval:input_type -> google.api.expr.conformance.v1alpha1.EvalRequest
	2,  // 17: google.api.expr.conformance.v1alpha1.ConformanceService.Parse:output_type -> google.api.expr.conformance.v1alpha1.ParseResponse
	4,  // 18: google.api.expr.conformance.v1alpha1.ConformanceService.Check:output_type -> google.api.expr.conformance.v1alpha1.CheckResponse
	6,  // 19: google.api.expr.conformance.v1alpha1.ConformanceService.Eval:output_type -> google.api.expr.conformance.v1alpha1.EvalResponse
	17, // [17:20] is the sub-list for method output_type
	14, // [14:17] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_google_api_expr_conformance_v1alpha1_conformance_service_proto_init() }
func file_google_api_expr_conformance_v1alpha1_conformance_service_proto_init() {
	if File_google_api_expr_conformance_v1alpha1_conformance_service_proto != nil {
		return
	}
	file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes[4].OneofWrappers = []any{
		(*EvalRequest_ParsedExpr)(nil),
		(*EvalRequest_CheckedExpr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDesc), len(file_google_api_expr_conformance_v1alpha1_conformance_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_api_expr_conformance_v1alpha1_conformance_service_proto_goTypes,
		DependencyIndexes: file_google_api_expr_conformance_v1alpha1_conformance_service_proto_depIdxs,
		EnumInfos:         file_google_api_expr_conformance_v1alpha1_conformance_service_proto_enumTypes,
		MessageInfos:      file_google_api_expr_conformance_v1alpha1_conformance_service_proto_msgTypes,
	}.Build()
	File_google_api_expr_conformance_v1alpha1_conformance_service_proto = out.File
	file_google_api_expr_conformance_v1alpha1_conformance_service_proto_goTypes = nil
	file_google_api_expr_conformance_v1alpha1_conformance_service_proto_depIdxs = nil
}
