// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: saas/api/tenant/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_DUPLICATE_TENANT_NAME   ErrorReason = 0
	ErrorReason_TENANT_NOT_FOUND        ErrorReason = 1
	ErrorReason_TENANT_FORBIDDEN        ErrorReason = 2
	ErrorReason_TENANT_NOT_READY        ErrorReason = 3
	ErrorReason_ADMIN_IDENTITY_REQUIRED ErrorReason = 4
	ErrorReason_ADMIN_PASSWORD_REQUIRED ErrorReason = 5
	ErrorReason_ADMIN_USERNAME_INVALID  ErrorReason = 6
	ErrorReason_ADMIN_EMAIL_INVALID     ErrorReason = 7
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "DUPLICATE_TENANT_NAME",
		1: "TENANT_NOT_FOUND",
		2: "TENANT_FORBIDDEN",
		3: "TENANT_NOT_READY",
		4: "ADMIN_IDENTITY_REQUIRED",
		5: "ADMIN_PASSWORD_REQUIRED",
		6: "ADMIN_USERNAME_INVALID",
		7: "ADMIN_EMAIL_INVALID",
	}
	ErrorReason_value = map[string]int32{
		"DUPLICATE_TENANT_NAME":   0,
		"TENANT_NOT_FOUND":        1,
		"TENANT_FORBIDDEN":        2,
		"TENANT_NOT_READY":        3,
		"ADMIN_IDENTITY_REQUIRED": 4,
		"ADMIN_PASSWORD_REQUIRED": 5,
		"ADMIN_USERNAME_INVALID":  6,
		"ADMIN_EMAIL_INVALID":     7,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_saas_api_tenant_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_saas_api_tenant_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_saas_api_tenant_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_saas_api_tenant_v1_error_reason_proto protoreflect.FileDescriptor

const file_saas_api_tenant_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"%saas/api/tenant/v1/error_reason.proto\x12\x12saas.api.tenant.v1\x1a\x13errors/errors.proto*\x8f\x02\n" +
	"\vErrorReason\x12\x1f\n" +
	"\x15DUPLICATE_TENANT_NAME\x10\x00\x1a\x04\xa8E\x90\x03\x12\x1a\n" +
	"\x10TENANT_NOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x12\x1a\n" +
	"\x10TENANT_FORBIDDEN\x10\x02\x1a\x04\xa8E\x93\x03\x12\x1a\n" +
	"\x10TENANT_NOT_READY\x10\x03\x1a\x04\xa8E\x93\x03\x12!\n" +
	"\x17ADMIN_IDENTITY_REQUIRED\x10\x04\x1a\x04\xa8E\x90\x03\x12!\n" +
	"\x17ADMIN_PASSWORD_REQUIRED\x10\x05\x1a\x04\xa8E\x90\x03\x12 \n" +
	"\x16ADMIN_USERNAME_INVALID\x10\x06\x1a\x04\xa8E\x90\x03\x12\x1d\n" +
	"\x13ADMIN_EMAIL_INVALID\x10\a\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03B.Z,github.com/go-saas/kit/saas/api/tenant/v1;v1b\x06proto3"

var (
	file_saas_api_tenant_v1_error_reason_proto_rawDescOnce sync.Once
	file_saas_api_tenant_v1_error_reason_proto_rawDescData []byte
)

func file_saas_api_tenant_v1_error_reason_proto_rawDescGZIP() []byte {
	file_saas_api_tenant_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_saas_api_tenant_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saas_api_tenant_v1_error_reason_proto_rawDesc), len(file_saas_api_tenant_v1_error_reason_proto_rawDesc)))
	})
	return file_saas_api_tenant_v1_error_reason_proto_rawDescData
}

var file_saas_api_tenant_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_saas_api_tenant_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: saas.api.tenant.v1.ErrorReason
}
var file_saas_api_tenant_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_saas_api_tenant_v1_error_reason_proto_init() }
func file_saas_api_tenant_v1_error_reason_proto_init() {
	if File_saas_api_tenant_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saas_api_tenant_v1_error_reason_proto_rawDesc), len(file_saas_api_tenant_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_saas_api_tenant_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_saas_api_tenant_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_saas_api_tenant_v1_error_reason_proto_enumTypes,
	}.Build()
	File_saas_api_tenant_v1_error_reason_proto = out.File
	file_saas_api_tenant_v1_error_reason_proto_goTypes = nil
	file_saas_api_tenant_v1_error_reason_proto_depIdxs = nil
}
