etcd:
  host:
    - "http://etcd:2379"  # Cambiado de 127.0.0.1:2379 a etcd:2379
  prefix: "/apisix"
  timeout: 30

apisix:
  enable_admin: true
  enable_admin_cors: true
  admin_listen:
    ip: 0.0.0.0
    port: 9180

http:
  listen:
    ip: 0.0.0.0
    port: 9080

nginx_config:
  worker_processes: auto