user:
  password_score_min: 0
  admin:
    username: admin
    password: "123456"
  idp: {}
  
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 60s
  health:
    enabled: true
    addr: 0.0.0.0:9001