app:
  host_display_name: GO SAAS KIT DEMO
  domain_format: ([-a-z0-9]+)\.saas\.nihaosaoya\.com

data:
  vfs:
    -
      public_url: https://saas.nihaosaoya.com/assets
      mount_path: "/"
      os:
        dir: ".assets"