// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: product/api/product/v1/product_internal.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/go-saas/kit/pkg/query"
	_ "github.com/go-saas/kit/product/api/category/v1"
	v1 "github.com/go-saas/kit/product/api/price/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInternalProductRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	ShortDesc       string                 `protobuf:"bytes,11,opt,name=short_desc,json=shortDesc,proto3" json:"short_desc,omitempty"`
	Desc            string                 `protobuf:"bytes,12,opt,name=desc,proto3" json:"desc,omitempty"`
	MainPic         *ProductMedia          `protobuf:"bytes,13,opt,name=main_pic,json=mainPic,proto3" json:"main_pic,omitempty"`
	Medias          []*ProductMedia        `protobuf:"bytes,14,rep,name=medias,proto3" json:"medias,omitempty"`
	Badges          []*Badge               `protobuf:"bytes,15,rep,name=badges,proto3" json:"badges,omitempty"`
	VisibleFrom     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=visible_from,json=visibleFrom,proto3" json:"visible_from,omitempty"`
	VisibleTo       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=visible_to,json=visibleTo,proto3" json:"visible_to,omitempty"`
	IsNew           bool                   `protobuf:"varint,18,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	MainCategoryKey *string                `protobuf:"bytes,40,opt,name=main_category_key,json=mainCategoryKey,proto3,oneof" json:"main_category_key,omitempty"`
	CategoryKeys    []string               `protobuf:"bytes,41,rep,name=category_keys,json=categoryKeys,proto3" json:"category_keys,omitempty"`
	Barcode         string                 `protobuf:"bytes,19,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Model           string                 `protobuf:"bytes,20,opt,name=model,proto3" json:"model,omitempty"`
	BrandId         *string                `protobuf:"bytes,21,opt,name=brand_id,json=brandId,proto3,oneof" json:"brand_id,omitempty"`
	IsSaleable      bool                   `protobuf:"varint,22,opt,name=is_saleable,json=isSaleable,proto3" json:"is_saleable,omitempty"`
	SaleableFrom    *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=saleable_from,json=saleableFrom,proto3" json:"saleable_from,omitempty"`
	SaleableTo      *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=saleable_to,json=saleableTo,proto3" json:"saleable_to,omitempty"`
	Keywords        []*Keyword             `protobuf:"bytes,25,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Prices          []*v1.PriceParams      `protobuf:"bytes,26,rep,name=prices,proto3" json:"prices,omitempty"`
	IsGiveaway      bool                   `protobuf:"varint,27,opt,name=is_giveaway,json=isGiveaway,proto3" json:"is_giveaway,omitempty"`
	Attributes      []*ProductAttribute    `protobuf:"bytes,43,rep,name=attributes,proto3" json:"attributes,omitempty"`
	MultiSku        bool                   `protobuf:"varint,50,opt,name=multi_sku,json=multiSku,proto3" json:"multi_sku,omitempty"`
	CampaignRules   []*CampaignRule        `protobuf:"bytes,60,rep,name=campaign_rules,json=campaignRules,proto3" json:"campaign_rules,omitempty"`
	NeedShipping    bool                   `protobuf:"varint,61,opt,name=need_shipping,json=needShipping,proto3" json:"need_shipping,omitempty"`
	Stocks          []*Stock               `protobuf:"bytes,62,rep,name=stocks,proto3" json:"stocks,omitempty"`
	Content         *structpb.Struct       `protobuf:"bytes,63,opt,name=content,proto3" json:"content,omitempty"`
	// internal extra fields
	ManageInfo    *ProductManageInfo `protobuf:"bytes,100,opt,name=manage_info,json=manageInfo,proto3" json:"manage_info,omitempty"`
	Active        bool               `protobuf:"varint,101,opt,name=active,proto3" json:"active,omitempty"`
	Internal      bool               `protobuf:"varint,102,opt,name=internal,proto3" json:"internal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInternalProductRequest) Reset() {
	*x = CreateInternalProductRequest{}
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInternalProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInternalProductRequest) ProtoMessage() {}

func (x *CreateInternalProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInternalProductRequest.ProtoReflect.Descriptor instead.
func (*CreateInternalProductRequest) Descriptor() ([]byte, []int) {
	return file_product_api_product_v1_product_internal_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInternalProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateInternalProductRequest) GetShortDesc() string {
	if x != nil {
		return x.ShortDesc
	}
	return ""
}

func (x *CreateInternalProductRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateInternalProductRequest) GetMainPic() *ProductMedia {
	if x != nil {
		return x.MainPic
	}
	return nil
}

func (x *CreateInternalProductRequest) GetMedias() []*ProductMedia {
	if x != nil {
		return x.Medias
	}
	return nil
}

func (x *CreateInternalProductRequest) GetBadges() []*Badge {
	if x != nil {
		return x.Badges
	}
	return nil
}

func (x *CreateInternalProductRequest) GetVisibleFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.VisibleFrom
	}
	return nil
}

func (x *CreateInternalProductRequest) GetVisibleTo() *timestamppb.Timestamp {
	if x != nil {
		return x.VisibleTo
	}
	return nil
}

func (x *CreateInternalProductRequest) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *CreateInternalProductRequest) GetMainCategoryKey() string {
	if x != nil && x.MainCategoryKey != nil {
		return *x.MainCategoryKey
	}
	return ""
}

func (x *CreateInternalProductRequest) GetCategoryKeys() []string {
	if x != nil {
		return x.CategoryKeys
	}
	return nil
}

func (x *CreateInternalProductRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *CreateInternalProductRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateInternalProductRequest) GetBrandId() string {
	if x != nil && x.BrandId != nil {
		return *x.BrandId
	}
	return ""
}

func (x *CreateInternalProductRequest) GetIsSaleable() bool {
	if x != nil {
		return x.IsSaleable
	}
	return false
}

func (x *CreateInternalProductRequest) GetSaleableFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleableFrom
	}
	return nil
}

func (x *CreateInternalProductRequest) GetSaleableTo() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleableTo
	}
	return nil
}

func (x *CreateInternalProductRequest) GetKeywords() []*Keyword {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *CreateInternalProductRequest) GetPrices() []*v1.PriceParams {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *CreateInternalProductRequest) GetIsGiveaway() bool {
	if x != nil {
		return x.IsGiveaway
	}
	return false
}

func (x *CreateInternalProductRequest) GetAttributes() []*ProductAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateInternalProductRequest) GetMultiSku() bool {
	if x != nil {
		return x.MultiSku
	}
	return false
}

func (x *CreateInternalProductRequest) GetCampaignRules() []*CampaignRule {
	if x != nil {
		return x.CampaignRules
	}
	return nil
}

func (x *CreateInternalProductRequest) GetNeedShipping() bool {
	if x != nil {
		return x.NeedShipping
	}
	return false
}

func (x *CreateInternalProductRequest) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

func (x *CreateInternalProductRequest) GetContent() *structpb.Struct {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CreateInternalProductRequest) GetManageInfo() *ProductManageInfo {
	if x != nil {
		return x.ManageInfo
	}
	return nil
}

func (x *CreateInternalProductRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CreateInternalProductRequest) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

type UpdateInternalProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *UpdateProduct         `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInternalProductRequest) Reset() {
	*x = UpdateInternalProductRequest{}
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInternalProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInternalProductRequest) ProtoMessage() {}

func (x *UpdateInternalProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInternalProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateInternalProductRequest) Descriptor() ([]byte, []int) {
	return file_product_api_product_v1_product_internal_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateInternalProductRequest) GetProduct() *UpdateProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *UpdateInternalProductRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type GetInternalProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInternalProductRequest) Reset() {
	*x = GetInternalProductRequest{}
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInternalProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInternalProductRequest) ProtoMessage() {}

func (x *GetInternalProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInternalProductRequest.ProtoReflect.Descriptor instead.
func (*GetInternalProductRequest) Descriptor() ([]byte, []int) {
	return file_product_api_product_v1_product_internal_proto_rawDescGZIP(), []int{2}
}

func (x *GetInternalProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteInternalProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInternalProductRequest) Reset() {
	*x = DeleteInternalProductRequest{}
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInternalProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInternalProductRequest) ProtoMessage() {}

func (x *DeleteInternalProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInternalProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteInternalProductRequest) Descriptor() ([]byte, []int) {
	return file_product_api_product_v1_product_internal_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteInternalProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteInternalProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInternalProductReply) Reset() {
	*x = DeleteInternalProductReply{}
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInternalProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInternalProductReply) ProtoMessage() {}

func (x *DeleteInternalProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInternalProductReply.ProtoReflect.Descriptor instead.
func (*DeleteInternalProductReply) Descriptor() ([]byte, []int) {
	return file_product_api_product_v1_product_internal_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteInternalProductReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInternalPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInternalPriceRequest) Reset() {
	*x = GetInternalPriceRequest{}
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInternalPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInternalPriceRequest) ProtoMessage() {}

func (x *GetInternalPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_api_product_v1_product_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInternalPriceRequest.ProtoReflect.Descriptor instead.
func (*GetInternalPriceRequest) Descriptor() ([]byte, []int) {
	return file_product_api_product_v1_product_internal_proto_rawDescGZIP(), []int{5}
}

func (x *GetInternalPriceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_product_api_product_v1_product_internal_proto protoreflect.FileDescriptor

const file_product_api_product_v1_product_internal_proto_rawDesc = "" +
	"\n" +
	"-product/api/product/v1/product_internal.proto\x12\x16product.api.product.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a(google/api/annotations/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\x1a\x15query/operation.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a#product/api/product/v1/common.proto\x1a&product/api/category/v1/category.proto\x1a$product/api/product/v1/product.proto\x1a product/api/price/v1/price.proto\"\xfe\n" +
	"\n" +
	"\x1cCreateInternalProductRequest\x12 \n" +
	"\x05title\x18\n" +
	" \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\x05title\x12\x1d\n" +
	"\n" +
	"short_desc\x18\v \x01(\tR\tshortDesc\x12\x12\n" +
	"\x04desc\x18\f \x01(\tR\x04desc\x12?\n" +
	"\bmain_pic\x18\r \x01(\v2$.product.api.product.v1.ProductMediaR\amainPic\x12<\n" +
	"\x06medias\x18\x0e \x03(\v2$.product.api.product.v1.ProductMediaR\x06medias\x125\n" +
	"\x06badges\x18\x0f \x03(\v2\x1d.product.api.product.v1.BadgeR\x06badges\x12=\n" +
	"\fvisible_from\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vvisibleFrom\x129\n" +
	"\n" +
	"visible_to\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tvisibleTo\x12\x15\n" +
	"\x06is_new\x18\x12 \x01(\bR\x05isNew\x12/\n" +
	"\x11main_category_key\x18( \x01(\tH\x00R\x0fmainCategoryKey\x88\x01\x01\x12#\n" +
	"\rcategory_keys\x18) \x03(\tR\fcategoryKeys\x12\x18\n" +
	"\abarcode\x18\x13 \x01(\tR\abarcode\x12\x14\n" +
	"\x05model\x18\x14 \x01(\tR\x05model\x12\x1e\n" +
	"\bbrand_id\x18\x15 \x01(\tH\x01R\abrandId\x88\x01\x01\x12\x1f\n" +
	"\vis_saleable\x18\x16 \x01(\bR\n" +
	"isSaleable\x12?\n" +
	"\rsaleable_from\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\fsaleableFrom\x12;\n" +
	"\vsaleable_to\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"saleableTo\x12;\n" +
	"\bkeywords\x18\x19 \x03(\v2\x1f.product.api.product.v1.KeywordR\bkeywords\x129\n" +
	"\x06prices\x18\x1a \x03(\v2!.product.api.price.v1.PriceParamsR\x06prices\x12\x1f\n" +
	"\vis_giveaway\x18\x1b \x01(\bR\n" +
	"isGiveaway\x12H\n" +
	"\n" +
	"attributes\x18+ \x03(\v2(.product.api.product.v1.ProductAttributeR\n" +
	"attributes\x12\x1b\n" +
	"\tmulti_sku\x182 \x01(\bR\bmultiSku\x12K\n" +
	"\x0ecampaign_rules\x18< \x03(\v2$.product.api.product.v1.CampaignRuleR\rcampaignRules\x12#\n" +
	"\rneed_shipping\x18= \x01(\bR\fneedShipping\x125\n" +
	"\x06stocks\x18> \x03(\v2\x1d.product.api.product.v1.StockR\x06stocks\x121\n" +
	"\acontent\x18? \x01(\v2\x17.google.protobuf.StructR\acontent\x12J\n" +
	"\vmanage_info\x18d \x01(\v2).product.api.product.v1.ProductManageInfoR\n" +
	"manageInfo\x12\x16\n" +
	"\x06active\x18e \x01(\bR\x06active\x12\x1a\n" +
	"\binternal\x18f \x01(\bR\binternalB\x14\n" +
	"\x12_main_category_keyB\v\n" +
	"\t_brand_id\"\xa9\x01\n" +
	"\x1cUpdateInternalProductRequest\x12L\n" +
	"\aproduct\x18\x01 \x01(\v2%.product.api.product.v1.UpdateProductB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\aproduct\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"7\n" +
	"\x19GetInternalProductRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\x02id\".\n" +
	"\x1cDeleteInternalProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x1aDeleteInternalProductReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x17GetInternalPriceRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\x02id2\xc1\x05\n" +
	"\x16ProductInternalService\x12m\n" +
	"\x13ListInternalProduct\x12*.product.api.product.v1.ListProductRequest\x1a(.product.api.product.v1.ListProductReply\"\x00\x12p\n" +
	"\x15CreateInternalProduct\x124.product.api.product.v1.CreateInternalProductRequest\x1a\x1f.product.api.product.v1.Product\"\x00\x12j\n" +
	"\x12GetInternalProduct\x121.product.api.product.v1.GetInternalProductRequest\x1a\x1f.product.api.product.v1.Product\"\x00\x12p\n" +
	"\x15UpdateInternalProduct\x124.product.api.product.v1.UpdateInternalProductRequest\x1a\x1f.product.api.product.v1.Product\"\x00\x12\x83\x01\n" +
	"\x15DeleteInternalProduct\x124.product.api.product.v1.DeleteInternalProductRequest\x1a2.product.api.product.v1.DeleteInternalProductReply\"\x00\x12b\n" +
	"\x10GetInternalPrice\x12/.product.api.product.v1.GetInternalPriceRequest\x1a\x1b.product.api.price.v1.Price\"\x00B2Z0github.com/go-saas/kit/product/api/product/v1;v1b\x06proto3"

var (
	file_product_api_product_v1_product_internal_proto_rawDescOnce sync.Once
	file_product_api_product_v1_product_internal_proto_rawDescData []byte
)

func file_product_api_product_v1_product_internal_proto_rawDescGZIP() []byte {
	file_product_api_product_v1_product_internal_proto_rawDescOnce.Do(func() {
		file_product_api_product_v1_product_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_api_product_v1_product_internal_proto_rawDesc), len(file_product_api_product_v1_product_internal_proto_rawDesc)))
	})
	return file_product_api_product_v1_product_internal_proto_rawDescData
}

var file_product_api_product_v1_product_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_product_api_product_v1_product_internal_proto_goTypes = []any{
	(*CreateInternalProductRequest)(nil), // 0: product.api.product.v1.CreateInternalProductRequest
	(*UpdateInternalProductRequest)(nil), // 1: product.api.product.v1.UpdateInternalProductRequest
	(*GetInternalProductRequest)(nil),    // 2: product.api.product.v1.GetInternalProductRequest
	(*DeleteInternalProductRequest)(nil), // 3: product.api.product.v1.DeleteInternalProductRequest
	(*DeleteInternalProductReply)(nil),   // 4: product.api.product.v1.DeleteInternalProductReply
	(*GetInternalPriceRequest)(nil),      // 5: product.api.product.v1.GetInternalPriceRequest
	(*ProductMedia)(nil),                 // 6: product.api.product.v1.ProductMedia
	(*Badge)(nil),                        // 7: product.api.product.v1.Badge
	(*timestamppb.Timestamp)(nil),        // 8: google.protobuf.Timestamp
	(*Keyword)(nil),                      // 9: product.api.product.v1.Keyword
	(*v1.PriceParams)(nil),               // 10: product.api.price.v1.PriceParams
	(*ProductAttribute)(nil),             // 11: product.api.product.v1.ProductAttribute
	(*CampaignRule)(nil),                 // 12: product.api.product.v1.CampaignRule
	(*Stock)(nil),                        // 13: product.api.product.v1.Stock
	(*structpb.Struct)(nil),              // 14: google.protobuf.Struct
	(*ProductManageInfo)(nil),            // 15: product.api.product.v1.ProductManageInfo
	(*UpdateProduct)(nil),                // 16: product.api.product.v1.UpdateProduct
	(*fieldmaskpb.FieldMask)(nil),        // 17: google.protobuf.FieldMask
	(*ListProductRequest)(nil),           // 18: product.api.product.v1.ListProductRequest
	(*ListProductReply)(nil),             // 19: product.api.product.v1.ListProductReply
	(*Product)(nil),                      // 20: product.api.product.v1.Product
	(*v1.Price)(nil),                     // 21: product.api.price.v1.Price
}
var file_product_api_product_v1_product_internal_proto_depIdxs = []int32{
	6,  // 0: product.api.product.v1.CreateInternalProductRequest.main_pic:type_name -> product.api.product.v1.ProductMedia
	6,  // 1: product.api.product.v1.CreateInternalProductRequest.medias:type_name -> product.api.product.v1.ProductMedia
	7,  // 2: product.api.product.v1.CreateInternalProductRequest.badges:type_name -> product.api.product.v1.Badge
	8,  // 3: product.api.product.v1.CreateInternalProductRequest.visible_from:type_name -> google.protobuf.Timestamp
	8,  // 4: product.api.product.v1.CreateInternalProductRequest.visible_to:type_name -> google.protobuf.Timestamp
	8,  // 5: product.api.product.v1.CreateInternalProductRequest.saleable_from:type_name -> google.protobuf.Timestamp
	8,  // 6: product.api.product.v1.CreateInternalProductRequest.saleable_to:type_name -> google.protobuf.Timestamp
	9,  // 7: product.api.product.v1.CreateInternalProductRequest.keywords:type_name -> product.api.product.v1.Keyword
	10, // 8: product.api.product.v1.CreateInternalProductRequest.prices:type_name -> product.api.price.v1.PriceParams
	11, // 9: product.api.product.v1.CreateInternalProductRequest.attributes:type_name -> product.api.product.v1.ProductAttribute
	12, // 10: product.api.product.v1.CreateInternalProductRequest.campaign_rules:type_name -> product.api.product.v1.CampaignRule
	13, // 11: product.api.product.v1.CreateInternalProductRequest.stocks:type_name -> product.api.product.v1.Stock
	14, // 12: product.api.product.v1.CreateInternalProductRequest.content:type_name -> google.protobuf.Struct
	15, // 13: product.api.product.v1.CreateInternalProductRequest.manage_info:type_name -> product.api.product.v1.ProductManageInfo
	16, // 14: product.api.product.v1.UpdateInternalProductRequest.product:type_name -> product.api.product.v1.UpdateProduct
	17, // 15: product.api.product.v1.UpdateInternalProductRequest.update_mask:type_name -> google.protobuf.FieldMask
	18, // 16: product.api.product.v1.ProductInternalService.ListInternalProduct:input_type -> product.api.product.v1.ListProductRequest
	0,  // 17: product.api.product.v1.ProductInternalService.CreateInternalProduct:input_type -> product.api.product.v1.CreateInternalProductRequest
	2,  // 18: product.api.product.v1.ProductInternalService.GetInternalProduct:input_type -> product.api.product.v1.GetInternalProductRequest
	1,  // 19: product.api.product.v1.ProductInternalService.UpdateInternalProduct:input_type -> product.api.product.v1.UpdateInternalProductRequest
	3,  // 20: product.api.product.v1.ProductInternalService.DeleteInternalProduct:input_type -> product.api.product.v1.DeleteInternalProductRequest
	5,  // 21: product.api.product.v1.ProductInternalService.GetInternalPrice:input_type -> product.api.product.v1.GetInternalPriceRequest
	19, // 22: product.api.product.v1.ProductInternalService.ListInternalProduct:output_type -> product.api.product.v1.ListProductReply
	20, // 23: product.api.product.v1.ProductInternalService.CreateInternalProduct:output_type -> product.api.product.v1.Product
	20, // 24: product.api.product.v1.ProductInternalService.GetInternalProduct:output_type -> product.api.product.v1.Product
	20, // 25: product.api.product.v1.ProductInternalService.UpdateInternalProduct:output_type -> product.api.product.v1.Product
	4,  // 26: product.api.product.v1.ProductInternalService.DeleteInternalProduct:output_type -> product.api.product.v1.DeleteInternalProductReply
	21, // 27: product.api.product.v1.ProductInternalService.GetInternalPrice:output_type -> product.api.price.v1.Price
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_product_api_product_v1_product_internal_proto_init() }
func file_product_api_product_v1_product_internal_proto_init() {
	if File_product_api_product_v1_product_internal_proto != nil {
		return
	}
	file_product_api_product_v1_common_proto_init()
	file_product_api_product_v1_product_proto_init()
	file_product_api_product_v1_product_internal_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_api_product_v1_product_internal_proto_rawDesc), len(file_product_api_product_v1_product_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_api_product_v1_product_internal_proto_goTypes,
		DependencyIndexes: file_product_api_product_v1_product_internal_proto_depIdxs,
		MessageInfos:      file_product_api_product_v1_product_internal_proto_msgTypes,
	}.Build()
	File_product_api_product_v1_product_internal_proto = out.File
	file_product_api_product_v1_product_internal_proto_goTypes = nil
	file_product_api_product_v1_product_internal_proto_depIdxs = nil
}
