apisix:
  node_listen: 9080
  enable_admin: true
  enable_admin_cors: true
  admin_listen:
    ip: 0.0.0.0
    port: 9180
  allow_admin:
    - 0.0.0.0/0

etcd:
  host:
    - "http://etcd:2379"
  prefix: "/apisix"
  timeout: 30

nginx_config:
  error_log_level: warn
  worker_processes: auto
