// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: google/api/policy.proto

package serviceconfig

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FieldPolicy with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FieldPolicy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FieldPolicy with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FieldPolicyMultiError, or
// nil if none found.
func (m *FieldPolicy) ValidateAll() error {
	return m.validate(true)
}

func (m *FieldPolicy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Selector

	// no validation rules for ResourcePermission

	// no validation rules for ResourceType

	if len(errors) > 0 {
		return FieldPolicyMultiError(errors)
	}

	return nil
}

// FieldPolicyMultiError is an error wrapping multiple validation errors
// returned by FieldPolicy.ValidateAll() if the designated constraints aren't met.
type FieldPolicyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FieldPolicyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FieldPolicyMultiError) AllErrors() []error { return m }

// FieldPolicyValidationError is the validation error returned by
// FieldPolicy.Validate if the designated constraints aren't met.
type FieldPolicyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FieldPolicyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FieldPolicyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FieldPolicyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FieldPolicyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FieldPolicyValidationError) ErrorName() string { return "FieldPolicyValidationError" }

// Error satisfies the builtin error interface
func (e FieldPolicyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFieldPolicy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FieldPolicyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FieldPolicyValidationError{}

// Validate checks the field values on MethodPolicy with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MethodPolicy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MethodPolicy with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MethodPolicyMultiError, or
// nil if none found.
func (m *MethodPolicy) ValidateAll() error {
	return m.validate(true)
}

func (m *MethodPolicy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Selector

	for idx, item := range m.GetRequestPolicies() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MethodPolicyValidationError{
						field:  fmt.Sprintf("RequestPolicies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MethodPolicyValidationError{
						field:  fmt.Sprintf("RequestPolicies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MethodPolicyValidationError{
					field:  fmt.Sprintf("RequestPolicies[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MethodPolicyMultiError(errors)
	}

	return nil
}

// MethodPolicyMultiError is an error wrapping multiple validation errors
// returned by MethodPolicy.ValidateAll() if the designated constraints aren't met.
type MethodPolicyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MethodPolicyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MethodPolicyMultiError) AllErrors() []error { return m }

// MethodPolicyValidationError is the validation error returned by
// MethodPolicy.Validate if the designated constraints aren't met.
type MethodPolicyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MethodPolicyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MethodPolicyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MethodPolicyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MethodPolicyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MethodPolicyValidationError) ErrorName() string { return "MethodPolicyValidationError" }

// Error satisfies the builtin error interface
func (e MethodPolicyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMethodPolicy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MethodPolicyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MethodPolicyValidationError{}
