// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: user/api/user/v1/user_admin.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/go-saas/kit/pkg/blob"
	_ "github.com/go-saas/kit/pkg/query"
	_ "github.com/go-saas/kit/user/api/role/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageOffset    int32                  `protobuf:"varint,1,opt,name=page_offset,json=pageOffset,proto3" json:"page_offset,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Sort          []string               `protobuf:"bytes,4,rep,name=sort,proto3" json:"sort,omitempty"`
	Fields        *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=fields,proto3" json:"fields,omitempty"`
	Filter        *UserFilter            `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListUsersRequest) Reset() {
	*x = AdminListUsersRequest{}
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListUsersRequest) ProtoMessage() {}

func (x *AdminListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListUsersRequest.ProtoReflect.Descriptor instead.
func (*AdminListUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_v1_user_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminListUsersRequest) GetPageOffset() int32 {
	if x != nil {
		return x.PageOffset
	}
	return 0
}

func (x *AdminListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminListUsersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *AdminListUsersRequest) GetSort() []string {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *AdminListUsersRequest) GetFields() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AdminListUsersRequest) GetFilter() *UserFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type AdminGetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetUserRequest) Reset() {
	*x = AdminGetUserRequest{}
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetUserRequest) ProtoMessage() {}

func (x *AdminGetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetUserRequest.ProtoReflect.Descriptor instead.
func (*AdminGetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_v1_user_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminGetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AdminListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSize     int32                  `protobuf:"varint,1,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	FilterSize    int32                  `protobuf:"varint,2,opt,name=filter_size,json=filterSize,proto3" json:"filter_size,omitempty"`
	Items         []*User                `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListUsersResponse) Reset() {
	*x = AdminListUsersResponse{}
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListUsersResponse) ProtoMessage() {}

func (x *AdminListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListUsersResponse.ProtoReflect.Descriptor instead.
func (*AdminListUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_api_user_v1_user_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminListUsersResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *AdminListUsersResponse) GetFilterSize() int32 {
	if x != nil {
		return x.FilterSize
	}
	return 0
}

func (x *AdminListUsersResponse) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

type AdminCreateUserRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Username        *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Name            *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Phone           *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email           *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Password        string                  `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                  `protobuf:"bytes,6,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	Birthday        *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Gender        Gender `protobuf:"varint,8,opt,name=gender,proto3,enum=user.api.user.v1.Gender" json:"gender,omitempty"`
	Avatar        string `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCreateUserRequest) Reset() {
	*x = AdminCreateUserRequest{}
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreateUserRequest) ProtoMessage() {}

func (x *AdminCreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreateUserRequest.ProtoReflect.Descriptor instead.
func (*AdminCreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_v1_user_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminCreateUserRequest) GetUsername() *wrapperspb.StringValue {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *AdminCreateUserRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *AdminCreateUserRequest) GetPhone() *wrapperspb.StringValue {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *AdminCreateUserRequest) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *AdminCreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminCreateUserRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *AdminCreateUserRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *AdminCreateUserRequest) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_UNKNOWN
}

func (x *AdminCreateUserRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type AdminUpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *AdminUpdateUser       `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateUserRequest) Reset() {
	*x = AdminUpdateUserRequest{}
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateUserRequest) ProtoMessage() {}

func (x *AdminUpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateUserRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_v1_user_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminUpdateUserRequest) GetUser() *AdminUpdateUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AdminUpdateUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type AdminUpdateUser struct {
	state    protoimpl.MessageState  `protogen:"open.v1"`
	Id       string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Name     *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Phone    *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email    *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Birthday *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Gender Gender `protobuf:"varint,7,opt,name=gender,proto3,enum=user.api.user.v1.Gender" json:"gender,omitempty"`
	// reset password
	Password        string `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string `protobuf:"bytes,9,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	Avatar          string `protobuf:"bytes,10,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminUpdateUser) Reset() {
	*x = AdminUpdateUser{}
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateUser) ProtoMessage() {}

func (x *AdminUpdateUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateUser.ProtoReflect.Descriptor instead.
func (*AdminUpdateUser) Descriptor() ([]byte, []int) {
	return file_user_api_user_v1_user_admin_proto_rawDescGZIP(), []int{5}
}

func (x *AdminUpdateUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminUpdateUser) GetUsername() *wrapperspb.StringValue {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *AdminUpdateUser) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *AdminUpdateUser) GetPhone() *wrapperspb.StringValue {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *AdminUpdateUser) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *AdminUpdateUser) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *AdminUpdateUser) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_UNKNOWN
}

func (x *AdminUpdateUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminUpdateUser) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *AdminUpdateUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type AdminDeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteUserRequest) Reset() {
	*x = AdminDeleteUserRequest{}
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteUserRequest) ProtoMessage() {}

func (x *AdminDeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteUserRequest.ProtoReflect.Descriptor instead.
func (*AdminDeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_api_user_v1_user_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AdminDeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AdminDeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteUserResponse) Reset() {
	*x = AdminDeleteUserResponse{}
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteUserResponse) ProtoMessage() {}

func (x *AdminDeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_user_v1_user_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteUserResponse.ProtoReflect.Descriptor instead.
func (*AdminDeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_api_user_v1_user_admin_proto_rawDescGZIP(), []int{7}
}

var File_user_api_user_v1_user_admin_proto protoreflect.FileDescriptor

const file_user_api_user_v1_user_admin_proto_rawDesc = "" +
	"\n" +
	"!user/api/user/v1/user_admin.proto\x12\x10user.api.user.v1\x1a(google/api/annotations/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1buser/api/role/v1/role.proto\x1a\x0fblob/blob.proto\x1a\x15query/operation.proto\x1a\x1buser/api/user/v1/user.proto\"\xeb\x01\n" +
	"\x15AdminListUsersRequest\x12\x1f\n" +
	"\vpage_offset\x18\x01 \x01(\x05R\n" +
	"pageOffset\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x12\n" +
	"\x04sort\x18\x04 \x03(\tR\x04sort\x122\n" +
	"\x06fields\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\x06fields\x124\n" +
	"\x06filter\x18\x06 \x01(\v2\x1c.user.api.user.v1.UserFilterR\x06filter\"1\n" +
	"\x13AdminGetUserRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\x02id\"\x86\x01\n" +
	"\x16AdminListUsersResponse\x12\x1d\n" +
	"\n" +
	"total_size\x18\x01 \x01(\x05R\ttotalSize\x12\x1f\n" +
	"\vfilter_size\x18\x02 \x01(\x05R\n" +
	"filterSize\x12,\n" +
	"\x05items\x18\x03 \x03(\v2\x16.user.api.user.v1.UserR\x05items\"\x8e\x04\n" +
	"\x16AdminCreateUserRequest\x12=\n" +
	"\busername\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\busername\x88\x01\x01\x125\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x01R\x04name\x88\x01\x01\x127\n" +
	"\x05phone\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueH\x02R\x05phone\x88\x01\x01\x12@\n" +
	"\x05email\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB\a\xfaB\x04r\x02`\x01H\x03R\x05email\x88\x01\x01\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x06 \x01(\tR\x0fconfirmPassword\x12;\n" +
	"\bbirthday\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\bbirthday\x88\x01\x01\x120\n" +
	"\x06gender\x18\b \x01(\x0e2\x18.user.api.user.v1.GenderR\x06gender\x12\x16\n" +
	"\x06avatar\x18\t \x01(\tR\x06avatarB\v\n" +
	"\t_usernameB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_emailB\v\n" +
	"\t_birthday\"\x99\x01\n" +
	"\x16AdminUpdateUserRequest\x12B\n" +
	"\x04user\x18\x02 \x01(\v2!.user.api.user.v1.AdminUpdateUserB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\x04user\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x9a\x04\n" +
	"\x0fAdminUpdateUser\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\x02id\x12=\n" +
	"\busername\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\busername\x88\x01\x01\x125\n" +
	"\x04name\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueH\x01R\x04name\x88\x01\x01\x127\n" +
	"\x05phone\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueH\x02R\x05phone\x88\x01\x01\x127\n" +
	"\x05email\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueH\x03R\x05email\x88\x01\x01\x12;\n" +
	"\bbirthday\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\bbirthday\x88\x01\x01\x120\n" +
	"\x06gender\x18\a \x01(\x0e2\x18.user.api.user.v1.GenderR\x06gender\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\t \x01(\tR\x0fconfirmPassword\x12\x16\n" +
	"\x06avatar\x18\n" +
	" \x01(\tR\x06avatarB\v\n" +
	"\t_usernameB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_emailB\v\n" +
	"\t_birthday\"(\n" +
	"\x16AdminDeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17AdminDeleteUserResponse2\xca\x05\n" +
	"\x10UserAdminService\x12\xa0\x01\n" +
	"\x0eListUsersAdmin\x12'.user.api.user.v1.AdminListUsersRequest\x1a(.user.api.user.v1.AdminListUsersResponse\";\x82\xd3\xe4\x93\x025Z\x1d:\x01*\"\x18/v1/user/admin/user/list\x12\x14/v1/user/admin/users\x12o\n" +
	"\fGetUserAdmin\x12%.user.api.user.v1.AdminGetUserRequest\x1a\x16.user.api.user.v1.User\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/user/admin/user/{id}\x12s\n" +
	"\x0fCreateUserAdmin\x12(.user.api.user.v1.AdminCreateUserRequest\x1a\x16.user.api.user.v1.User\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/user/admin/user\x12\xa1\x01\n" +
	"\x0fUpdateUserAdmin\x12(.user.api.user.v1.AdminUpdateUserRequest\x1a\x16.user.api.user.v1.User\"L\x82\xd3\xe4\x93\x02F:\x01*Z\":\x01*2\x1d/v1/user/admin/user/{user.id}\x1a\x1d/v1/user/admin/user/{user.id}\x12\x88\x01\n" +
	"\x0fDeleteUserAdmin\x12(.user.api.user.v1.AdminDeleteUserRequest\x1a).user.api.user.v1.AdminDeleteUserResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/v1/user/admin/user/{id}B,Z*github.com/go-saas/kit/user/api/user/v1;v1b\x06proto3"

var (
	file_user_api_user_v1_user_admin_proto_rawDescOnce sync.Once
	file_user_api_user_v1_user_admin_proto_rawDescData []byte
)

func file_user_api_user_v1_user_admin_proto_rawDescGZIP() []byte {
	file_user_api_user_v1_user_admin_proto_rawDescOnce.Do(func() {
		file_user_api_user_v1_user_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_api_user_v1_user_admin_proto_rawDesc), len(file_user_api_user_v1_user_admin_proto_rawDesc)))
	})
	return file_user_api_user_v1_user_admin_proto_rawDescData
}

var file_user_api_user_v1_user_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_api_user_v1_user_admin_proto_goTypes = []any{
	(*AdminListUsersRequest)(nil),   // 0: user.api.user.v1.AdminListUsersRequest
	(*AdminGetUserRequest)(nil),     // 1: user.api.user.v1.AdminGetUserRequest
	(*AdminListUsersResponse)(nil),  // 2: user.api.user.v1.AdminListUsersResponse
	(*AdminCreateUserRequest)(nil),  // 3: user.api.user.v1.AdminCreateUserRequest
	(*AdminUpdateUserRequest)(nil),  // 4: user.api.user.v1.AdminUpdateUserRequest
	(*AdminUpdateUser)(nil),         // 5: user.api.user.v1.AdminUpdateUser
	(*AdminDeleteUserRequest)(nil),  // 6: user.api.user.v1.AdminDeleteUserRequest
	(*AdminDeleteUserResponse)(nil), // 7: user.api.user.v1.AdminDeleteUserResponse
	(*fieldmaskpb.FieldMask)(nil),   // 8: google.protobuf.FieldMask
	(*UserFilter)(nil),              // 9: user.api.user.v1.UserFilter
	(*User)(nil),                    // 10: user.api.user.v1.User
	(*wrapperspb.StringValue)(nil),  // 11: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
	(Gender)(0),                     // 13: user.api.user.v1.Gender
}
var file_user_api_user_v1_user_admin_proto_depIdxs = []int32{
	8,  // 0: user.api.user.v1.AdminListUsersRequest.fields:type_name -> google.protobuf.FieldMask
	9,  // 1: user.api.user.v1.AdminListUsersRequest.filter:type_name -> user.api.user.v1.UserFilter
	10, // 2: user.api.user.v1.AdminListUsersResponse.items:type_name -> user.api.user.v1.User
	11, // 3: user.api.user.v1.AdminCreateUserRequest.username:type_name -> google.protobuf.StringValue
	11, // 4: user.api.user.v1.AdminCreateUserRequest.name:type_name -> google.protobuf.StringValue
	11, // 5: user.api.user.v1.AdminCreateUserRequest.phone:type_name -> google.protobuf.StringValue
	11, // 6: user.api.user.v1.AdminCreateUserRequest.email:type_name -> google.protobuf.StringValue
	12, // 7: user.api.user.v1.AdminCreateUserRequest.birthday:type_name -> google.protobuf.Timestamp
	13, // 8: user.api.user.v1.AdminCreateUserRequest.gender:type_name -> user.api.user.v1.Gender
	5,  // 9: user.api.user.v1.AdminUpdateUserRequest.user:type_name -> user.api.user.v1.AdminUpdateUser
	8,  // 10: user.api.user.v1.AdminUpdateUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	11, // 11: user.api.user.v1.AdminUpdateUser.username:type_name -> google.protobuf.StringValue
	11, // 12: user.api.user.v1.AdminUpdateUser.name:type_name -> google.protobuf.StringValue
	11, // 13: user.api.user.v1.AdminUpdateUser.phone:type_name -> google.protobuf.StringValue
	11, // 14: user.api.user.v1.AdminUpdateUser.email:type_name -> google.protobuf.StringValue
	12, // 15: user.api.user.v1.AdminUpdateUser.birthday:type_name -> google.protobuf.Timestamp
	13, // 16: user.api.user.v1.AdminUpdateUser.gender:type_name -> user.api.user.v1.Gender
	0,  // 17: user.api.user.v1.UserAdminService.ListUsersAdmin:input_type -> user.api.user.v1.AdminListUsersRequest
	1,  // 18: user.api.user.v1.UserAdminService.GetUserAdmin:input_type -> user.api.user.v1.AdminGetUserRequest
	3,  // 19: user.api.user.v1.UserAdminService.CreateUserAdmin:input_type -> user.api.user.v1.AdminCreateUserRequest
	4,  // 20: user.api.user.v1.UserAdminService.UpdateUserAdmin:input_type -> user.api.user.v1.AdminUpdateUserRequest
	6,  // 21: user.api.user.v1.UserAdminService.DeleteUserAdmin:input_type -> user.api.user.v1.AdminDeleteUserRequest
	2,  // 22: user.api.user.v1.UserAdminService.ListUsersAdmin:output_type -> user.api.user.v1.AdminListUsersResponse
	10, // 23: user.api.user.v1.UserAdminService.GetUserAdmin:output_type -> user.api.user.v1.User
	10, // 24: user.api.user.v1.UserAdminService.CreateUserAdmin:output_type -> user.api.user.v1.User
	10, // 25: user.api.user.v1.UserAdminService.UpdateUserAdmin:output_type -> user.api.user.v1.User
	7,  // 26: user.api.user.v1.UserAdminService.DeleteUserAdmin:output_type -> user.api.user.v1.AdminDeleteUserResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_user_api_user_v1_user_admin_proto_init() }
func file_user_api_user_v1_user_admin_proto_init() {
	if File_user_api_user_v1_user_admin_proto != nil {
		return
	}
	file_user_api_user_v1_user_proto_init()
	file_user_api_user_v1_user_admin_proto_msgTypes[3].OneofWrappers = []any{}
	file_user_api_user_v1_user_admin_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_api_user_v1_user_admin_proto_rawDesc), len(file_user_api_user_v1_user_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_api_user_v1_user_admin_proto_goTypes,
		DependencyIndexes: file_user_api_user_v1_user_admin_proto_depIdxs,
		MessageInfos:      file_user_api_user_v1_user_admin_proto_msgTypes,
	}.Build()
	File_user_api_user_v1_user_admin_proto = out.File
	file_user_api_user_v1_user_admin_proto_goTypes = nil
	file_user_api_user_v1_user_admin_proto_depIdxs = nil
}
