apisix:
  node_listen: 9080
  enable_admin: true
  admin_listen:
    ip: 0.0.0.0
    port: 9180
  allow_admin:
    - 0.0.0.0/0

# Configuración para modo standalone (sin etcd)
deployment:
  role: traditional
  role_traditional:
    config_provider: yaml
  admin:
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin

# Definir rutas estáticas
routes:
  -
    id: 1
    uri: "/v1/sys/menus/*"
    upstream:
      type: roundrobin
      nodes:
        "user:8000": 1
  -
    id: 2
    uri: "/v1/*"
    upstream:
      type: roundrobin
      nodes:
        "user:8000": 1
