app:
  name: saas
  version: "1.0"
  env: dev
  host_display_name: RANTIPAY-SAAS
server:
  http:
    addr: 0.0.0.0:8001
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 60s
services:
  registry:
    type: etcd
    endpoint: http://localhost:2379
  endpoints:
    user:
      address: localhost:9000
data:
  endpoints:
    databases:
      default:
        driver: mysql
        source: root:rantipay123@tcp(localhost:3306)/rantipay?parseTime=true&loc=Local&charset=utf8mb4&interpolateParams=true
    redis:
      default:
        addrs: ["localhost:6379"]
        password: rantipay123
    events:
      default:
        topic: kit
        addr: ""
        type: ""
      saas:
        group: saas-golang
security:
  jwt:
    expire_in: 2592000s
    secret: rantipay-jwt-super-secret-key
logging:
  level: debug
event:
  driver: ""