FROM golang:1.20 AS builder

WORKDIR /app
COPY . .

# Compilar directamente sin usar Makefile
RUN cd cmd && go build -o ../user

# Etapa final
FROM debian:stable-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/user /app/user
COPY --from=builder /app/configs /app/configs
COPY --from=builder /app/i18n /app/i18n

EXPOSE 8000 9000
ENTRYPOINT ["/app/user", "-conf", "/data/conf/user.yaml"]
