FROM golang:1.20 as builder

WORKDIR /app
COPY . .

# Compilar el binario
RUN go mod tidy && \
    cd cmd/user && \
    go build -o user .

FROM debian:stable-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/cmd/user/user /app/user

EXPOSE 8000 9000
CMD ["/app/user", "-conf", "/data/conf/user.yaml"]
