server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 60s
data:
  database:
    driver: mysql
    source: root:youShouldChangeThis@tcp(mysqld:3306)/kit?parseTime=true&loc=Local&charset=utf8mb4&interpolateParams=true
  redis:
    addr: redis:6379
    password: youShouldChangeThis
    db: 0
security:
  jwt:
    expire_in: 2592000s # 30 days
    secret: youShouldChangeThis
  security_cookie:
    hash_key: youShouldChangeThis
user:
  password_score_min: 0
  admin:
    username: admin@rantipay.com
    password: "Admin123!"
logging:
  level: debug
